import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {

  static Future<void> generateReport(
    File image,
    Map<String, dynamic> result,
    String userName,
    String explanation, // 🔥 from ResultScreen
  ) async {

    final pdf = pw.Document();
    final imageBytes = await image.readAsBytes();

    final rec = result["recommendation"] ?? {};
    final preventive = rec["preventive"] ?? [];

    final isHealthy = result["status"] == "healthy";

    // ================= PAGE 1 =================
    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(25),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [

              // HEADER
              pw.Container(
                padding: const pw.EdgeInsets.all(15),
                decoration: pw.BoxDecoration(
                  color: PdfColors.green100,
                  borderRadius: pw.BorderRadius.circular(12),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [

                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text("AGROVEDA",
                            style: pw.TextStyle(
                                fontSize: 26,
                                fontWeight: pw.FontWeight.bold,
                                color: PdfColors.green800)),
                        pw.Text("AI Disease Diagnosis Report"),
                      ],
                    ),

                    pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.end,
                      children: [
                        pw.Text("User: $userName"),
                        pw.Text(
                            "Date: ${DateTime.now().toString().split(" ")[0]}"),
                      ],
                    )
                  ],
                ),
              ),

              pw.SizedBox(height: 20),

              pw.Text("Scanned Leaf Image",
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),

              pw.SizedBox(height: 10),

              pw.Center(
                child: pw.Image(
                  pw.MemoryImage(imageBytes),
                  height: 180,
                ),
              ),

              pw.SizedBox(height: 20),

              pw.Text("Diagnosis Summary",
                  style: pw.TextStyle(
                      fontSize: 16,
                      fontWeight: pw.FontWeight.bold)),

              pw.SizedBox(height: 10),

              pw.Table(
                border: pw.TableBorder.all(),
                children: [

                  row("Plant", result["plant"]),
                  row("Disease",
                      isHealthy ? "Healthy Leaf" : result["disease"]),
                  row("Confidence",
                      "${(result["confidence"] ?? 0).toStringAsFixed(2)}%"),
                  row("Pathogen", rec["pathogen"]),
                  row("Chemical", rec["chemical"]),
                  row("Dosage", rec["dosage"]),
                  row("Frequency", rec["frequency"]),
                  row("Spray Volume", rec["spray_volume"]),
                  row("PHI Days", rec["phi_days"]),
                  row("Organic", rec["organic"]),
                ],
              ),

              pw.SizedBox(height: 20),

              if (preventive.isNotEmpty)
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text("Preventive Measures",
                        style: pw.TextStyle(
                            fontSize: 16,
                            fontWeight: pw.FontWeight.bold)),

                    pw.SizedBox(height: 8),

                    ...preventive.map<pw.Widget>((e) =>
                        pw.Bullet(text: e.toString()))
                  ],
                ),
            ],
          );
        },
      ),
    );

    // ================= PAGE 2+ (🔥 FIXED WITH MULTIPAGE) =================
    pdf.addPage(
      pw.MultiPage(
        margin: const pw.EdgeInsets.all(25),
        build: (pw.Context context) => [

          pw.Text("Detailed AI Analysis",
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.green800,
              )),

          pw.SizedBox(height: 15),

          pw.Text(
            explanation, // 🔥 FULL TEXT WILL NOW SHOW
            style: const pw.TextStyle(fontSize: 12),
          ),

          pw.SizedBox(height: 20),

          pw.Divider(),

          pw.Center(
            child: pw.Text(
              "Generated by AGROVEDA AI System",
              style: const pw.TextStyle(fontSize: 10),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  static pw.TableRow row(String title, dynamic value) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(title,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(8),
          child: pw.Text(value?.toString() ?? "N/A"),
        ),
      ],
    );
  }
}